"""Alert model - persisted operational alerts generated by the alert engine."""

from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import JSON, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base
from app.models.mixins import IntPKMixin, TimestampMixin

JSONType = JSON().with_variant(JSONB(), "postgresql")


class AlertSeverity(enum.StrEnum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class AlertStatus(enum.StrEnum):
    OPEN = "open"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class Alert(IntPKMixin, TimestampMixin, Base):
    """An operational alert about an account/campaign/keyword/ad/search term.

    Alerts are deduplicated by ``dedupe_key``: re-running the engine refreshes an
    existing OPEN alert (``last_seen_at``, current value) rather than duplicating
    it. When a condition clears, the alert can be auto-resolved.
    """

    __tablename__ = "alerts"

    account_id: Mapped[int | None] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), index=True
    )
    entity_type: Mapped[str] = mapped_column(String(32), index=True)  # campaign/keyword/...
    entity_id: Mapped[int | None] = mapped_column(index=True)  # internal PK of entity
    entity_name: Mapped[str | None] = mapped_column(String(512))

    alert_type: Mapped[str] = mapped_column(String(48), index=True)  # CTR_DROP, ...
    severity: Mapped[str] = mapped_column(
        String(16), default=AlertSeverity.MEDIUM.value, index=True
    )
    status: Mapped[str] = mapped_column(String(16), default=AlertStatus.OPEN.value, index=True)

    title: Mapped[str] = mapped_column(String(255))
    description: Mapped[str | None] = mapped_column(Text)
    suggested_action: Mapped[str | None] = mapped_column(Text)

    metric_value: Mapped[float | None] = mapped_column(Numeric(18, 4))
    threshold_value: Mapped[float | None] = mapped_column(Numeric(18, 4))

    # Stable identity across evaluations for dedupe (unique).
    dedupe_key: Mapped[str] = mapped_column(String(255), unique=True, index=True)

    first_seen_at: Mapped[datetime] = mapped_column(server_default=func.now())
    last_seen_at: Mapped[datetime] = mapped_column(server_default=func.now())
    resolved_at: Mapped[datetime | None]

    details: Mapped[dict | None] = mapped_column(JSONType)
